---
- name: brave repo
  become: true
  ansible.builtin.yum_repository:
    name: brave
    description: Brave Browser
    baseurl: https://brave-browser-rpm-release.s3.brave.com/$basearch
    enabled: true
    gpgcheck: true
    gpgkey: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

- name: install brave
  become: true
  ansible.builtin.dnf:
    name: brave-browser
    update_cache: true
