---
- name: docker repo
  become: true
  ansible.builtin.yum_repository:
    name: docker
    baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    description: Docker CE Stable
    enabled: true
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/fedora/gpg

- name: install packages
  become: true
  ansible.builtin.dnf:
    name: "{{ packages }}"
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - docker-buildx-plugin

- name: ensure docker group exists
  become: true
  ansible.builtin.group:
    name: docker

- name: add my user to docker group
  become: true
  ansible.builtin.user:
    name: davido
    groups: docker
    append: true

- name: start docker service
  become: true
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started

- name: start containerd service
  become: true
  ansible.builtin.service:
    name: containerd
    enabled: true
    state: started
